name: Promote Cloudflare Build
on:
  workflow_dispatch:
    inputs:
      source_dnslink:
        description: 'Copy value from record ID'
        required: true
        default: '_dnslink.ipfs-staging'
      dest_dnslink:
        description: 'to record ID'
        required: true
        default: '_dnslink.ipfs-dex'

jobs:
  copy_dnslink:
    runs-on: ubuntu-latest

    steps:
      - name: Get value of given dnslink and set to env.DNSLINK_RECORD
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_TOKEN_ZONE_ID }}
        shell: bash
        run: |
          response=$(curl \
            -H "Authorization: Bearer $CLOUDFLARE_TOKEN" \
            -H "Content-Type: application/json" \
            -s "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records?name=${{github.event.inputs.source_dnslink}}.sifchain.finance")

          success=$(jq -r  '.success' <<< "${response}" )

          echo "Response: (echo $response | jq)"
          if [ $success != "true" ]; then
            echo "Pages Update: Failed to read record '${{github.event.inputs.source_dnslink}}'"
            errors=$(jq -r  '.errors' <<< "${response}")
            exit 1
          fi

          DNSLINK_RECORD=$(jq -r  '.result[0].content' <<< "${response}" )
          echo "$DNSLINK_RECORD"
          echo "RECORD_DOMAIN=sifchain.finance" >> $GITHUB_ENV
          echo "RECORD_NAME=${{github.events.inputs.dest_dnslink}}" >> $GITHUB_ENV
          echo "DNSLINK_RECORD=$DNSLINK_RECORD" >> $GITHUB_ENV
          echo "env: $(cat $GITHUB_ENV)"

      - name: Update cloudflare DNSLink
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_TOKEN_ZONE_ID }}
        id: dnslink
        uses: textileio/cloudflare-update-dnslink@master
        with:
          cid: ${{ env.DNSLINK_RECORD }}
